---
stages:
- name: Build Stage
  inputs:
  - type: git
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: maven
    script: |-
      #!/bin/bash
      mvn -B package
    enable_tests: true
    test_file_pattern: 12-factor-application/target/test-reports/unit/TEST-*.xml
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared CloudantDBFor12Factor
      cf push "${CF_APP}" -p 12-factor-wlpcfg/servers/12FactorAppServer/12FactorAppServer.zip -f ./src/main/resources/
