server:
  port: 9000
spring:
  application:
    name: cf-mysql-java-broker
  datasource:
    url: jdbc:mysql://192.168.5.147:3306/Cloud
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  main:
    show_banner: false
